# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'history_shit.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_history(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(542, 647)
        Dialog.setStyleSheet("background:#e9fadc;")
        self.list_history = QtWidgets.QListView(Dialog)
        self.list_history.setGeometry(QtCore.QRect(10, 10, 321, 621))
        self.list_history.setStyleSheet("background: white; border: 2px solid #13bd4b;")
        self.list_history.setObjectName("list_history")
        self.btn_exit = QtWidgets.QPushButton(Dialog)
        self.btn_exit.setGeometry(QtCore.QRect(380, 600, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.btn_exit.setFont(font)
        self.btn_exit.setStyleSheet("background: white; border: 2px solid #13bd4b;")
        self.btn_exit.setObjectName("btn_exit")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(340, 10, 191, 211))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_clear_all = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(9)
        self.btn_clear_all.setFont(font)
        self.btn_clear_all.setObjectName("btn_clear_all")
        self.verticalLayout.addWidget(self.btn_clear_all)
        self.btn_clear_one = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(9)
        self.btn_clear_one.setFont(font)
        self.btn_clear_one.setObjectName("btn_clear_one")
        self.verticalLayout.addWidget(self.btn_clear_one)
        self.btn_3 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(9)
        self.btn_3.setFont(font)
        self.btn_3.setObjectName("btn_3")
        self.verticalLayout.addWidget(self.btn_3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btn_exit.setText(_translate("Dialog", "Выйти"))
        self.btn_clear_all.setText(_translate("Dialog", "Очистить историю"))
        self.btn_clear_one.setText(_translate("Dialog", "Очистить последнюю запись"))
        self.btn_3.setText(_translate("Dialog", "PushButton"))


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ex = Ui_Dialog_history()
    ex.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
