# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'history_shit.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import json
import sys

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_history(object):
    def setupUi(self, Dialog):
        self.list_history = QtWidgets.QListView(Dialog)
        self.list_history.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.list_history.setGeometry(QtCore.QRect(10, 10, 520, 680))
        self.list_history.setStyleSheet("background: white; border: 2px solid #13bd4b;")
        self.list_history.setObjectName("list_history")
        self.btn_exit = QtWidgets.QPushButton(Dialog)
        self.btn_exit.setGeometry(QtCore.QRect(380, 700, 150, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.btn_exit.setFont(font)
        self.btn_exit.setStyleSheet("background: white; border: 2px solid #13bd4b;")
        self.btn_exit.setObjectName("btn_exit")
        self.btn_clear_all = QtWidgets.QPushButton(Dialog)
        self.btn_clear_all.setGeometry(QtCore.QRect(10, 700, 160, 31))
        self.btn_clear_all.setFont(font)
        self.btn_clear_all.setStyleSheet("background: white; border: 2px solid #13bd4b;")
        self.btn_clear_all.setObjectName("btn_clear_all")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btn_exit.setText(_translate("Dialog", "Выйти"))
        self.btn_clear_all.setText(_translate("Dialog", "Очистить историю"))

    def widget_off(self):
        self.btn_clear_all.close()
        self.btn_exit.close()
        self.list_history.close()

    def widget_on(self, dialog, history):
        dialog.resize(540, 750)
        self.btn_exit.show()

        history = json.loads(history)
        history = ['\t'.join(element) for element in history]
        model = QtGui.QStandardItemModel()
        self.list_history.setModel(model)
        for element in history:
            item = QtGui.QStandardItem(element)
            model.appendRow(item)
        self.list_history.show()

        self.btn_clear_all.show()


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ex = Ui_Dialog_history()
    ex.setupUi(MainWindow)
    MainWindow.show()
    ex.widget_on(MainWindow, '[]')
    sys.exit(app.exec_())
