# -*- coding: utf-8 -*-

import sys

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setStyleSheet("background: white;")
        self.nick_line = QtWidgets.QLineEdit(Dialog)
        self.nick_line.setGeometry(QtCore.QRect(20, 90, 339, 29))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.nick_line.sizePolicy().hasHeightForWidth())
        self.nick_line.setSizePolicy(sizePolicy)
        self.nick_line.setStyleSheet("background: white; border: 2px solid #13bd4b; border-radius: 8px;")
        self.nick_line.setObjectName("lineEdit_4")
        self.register_button = QtWidgets.QPushButton(Dialog)
        self.register_button.setGeometry(QtCore.QRect(220, 530, 131, 31))
        self.register_button.setObjectName("pushButton_2")
        self.label_reg = QtWidgets.QLabel(Dialog)
        self.label_reg.setGeometry(QtCore.QRect(130, 40, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_reg.setFont(font)
        self.label_reg.setObjectName("label")
        self.label_2_reg = QtWidgets.QLabel(Dialog)
        self.label_2_reg.setGeometry(QtCore.QRect(150, 160, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2_reg.setFont(font)
        self.label_2_reg.setObjectName("label_2")
        self.label_3_reg = QtWidgets.QLabel(Dialog)
        self.label_3_reg.setGeometry(QtCore.QRect(140, 260, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3_reg.setFont(font)
        self.label_3_reg.setObjectName("label_3")
        self.email_register_line = QtWidgets.QLineEdit(Dialog)
        self.email_register_line.setGeometry(QtCore.QRect(20, 210, 339, 29))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.email_register_line.sizePolicy().hasHeightForWidth())
        self.email_register_line.setSizePolicy(sizePolicy)
        self.email_register_line.setStyleSheet("background: white; border: 2px solid #13bd4b; border-radius: 8px;")
        self.email_register_line.setObjectName("lineEdit_5")
        self.password_register_line = QtWidgets.QLineEdit(Dialog)
        self.password_register_line.setGeometry(QtCore.QRect(20, 320, 339, 29))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.password_register_line.sizePolicy().hasHeightForWidth())
        self.password_register_line.setSizePolicy(sizePolicy)
        self.password_register_line.setStyleSheet("background: white; border: 2px solid #13bd4b; border-radius: 8px;")
        self.password_register_line.setObjectName("lineEdit_6")
        self.repeat_password_line = QtWidgets.QLineEdit(Dialog)
        self.repeat_password_line.setGeometry(QtCore.QRect(20, 450, 339, 29))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.repeat_password_line.sizePolicy().hasHeightForWidth())
        self.repeat_password_line.setSizePolicy(sizePolicy)
        self.repeat_password_line.setStyleSheet("background: white; border: 2px solid #13bd4b; border-radius: 8px;")
        self.repeat_password_line.setText("")
        self.repeat_password_line.setObjectName("lineEdit_7")
        self.label_4_reg = QtWidgets.QLabel(Dialog)
        self.label_4_reg.setGeometry(QtCore.QRect(120, 390, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4_reg.setFont(font)
        self.label_4_reg.setObjectName("label_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.register_button.setText(_translate("Dialog", "Зарегестрироваться"))
        self.label_reg.setText(_translate("Dialog", "nickname"))
        self.label_2_reg.setText(_translate("Dialog", "email"))
        self.label_3_reg.setText(_translate("Dialog", "password"))
        self.label_4_reg.setText(_translate("Dialog", "repeat password"))

    def widget_off(self):
        self.register_button.close()
        self.label_reg.close()
        self.nick_line.close()
        self.password_register_line.close()
        self.repeat_password_line.close()
        self.email_register_line.close()
        self.label_2_reg.close()
        self.label_3_reg.close()
        self.label_4_reg.close()

    def widget_on(self):
        self.register_button.show()
        self.label_reg.show()
        self.nick_line.show()
        self.password_register_line.show()
        self.repeat_password_line.show()
        self.email_register_line.show()
        self.label_2_reg.show()
        self.label_3_reg.show()
        self.label_4_reg.show()


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ex = Ui_Dialog()
    ex.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
